# Generated by Django 2.2 on 2019-07-30 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Название:')),
                ('age_from', models.IntegerField(db_index=True, verbose_name='Со скольки лет:')),
                ('age_up', models.IntegerField(blank=True, db_index=True, verbose_name='До скольки лет:')),
                ('description', models.TextField(db_index=True, verbose_name='Описание:')),
                ('image', models.ImageField(db_index=True, upload_to='tng_images/', verbose_name='Картинка:')),
                ('company', models.CharField(db_index=True, max_length=100, verbose_name='Организация:')),
                ('adress', models.CharField(db_index=True, max_length=100, verbose_name='Адрес:')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон:')),
                ('website', models.CharField(blank=True, max_length=100, verbose_name='Сайт:')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта:')),
                ('price', models.CharField(default='Бесплатно', max_length=50, verbose_name='Цена:')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('available', models.BooleanField(default=True)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.City', verbose_name='Город:')),
                ('gender', models.ForeignKey(on_delete=True, to='catalog.Gender', verbose_name='Возраст:')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.SubCategory', verbose_name='Категория:')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='general_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.GeneralCategory'),
        ),
    ]
