# Generated by Django 2.2 on 2019-06-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tng',
            name='city',
        ),
    ]
