# Generated by Django 2.2.4 on 2019-08-22 18:30

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190821_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tng',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True),
        ),
    ]
