# Generated by Django 2.2 on 2019-06-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190620_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tng',
            name='city',
            field=models.CharField(db_index=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
