# Generated by Django 2.2 on 2019-06-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190620_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='С какого возраста:'),
        ),
        migrations.AlterField(
            model_name='tng',
            name='adress',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Адрес:'),
        ),
        migrations.AlterField(
            model_name='tng',
            name='city',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Город:'),
        ),
        migrations.AlterField(
            model_name='tng',
            name='description',
            field=models.TextField(db_index=True, verbose_name='Описание:'),
        ),
        migrations.AlterField(
            model_name='tng',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта:'),
        ),
        migrations.AlterField(
            model_name='tng',
            name='gender',
            field=models.ForeignKey(on_delete=True, to='catalog.Gender', verbose_name='Возраст:'),
        ),
        migrations.AlterField(
            model_name='tng',
            name='image',
            field=models.ImageField(db_index=True, upload_to='tng_images/', verbose_name='Картинка:'),
        ),
        migrations.AlterField(
            model_name='tng',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Телефон:'),
        ),
        migrations.AlterField(
            model_name='tng',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена:'),
        ),
        migrations.AlterField(
            model_name='tng',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название:'),
        ),
        migrations.AlterField(
            model_name='tng',
            name='website',
            field=models.CharField(max_length=100, verbose_name='Сайт:'),
        ),
    ]
