# Generated by Django 2.2.4 on 2019-08-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190822_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tng',
            name='company',
            field=models.CharField(db_index=True, max_length=99, verbose_name='Организация:'),
        ),
    ]
