# Generated by Django 2.2 on 2019-06-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190620_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tng',
            name='age',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Со скольки лет:'),
        ),
        migrations.DeleteModel(
            name='Age',
        ),
    ]
