# Generated by Django 2.2 on 2019-06-20 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190620_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tng',
            name='price',
            field=models.CharField(default='Бесплатно', max_length=50, verbose_name='Цена:'),
        ),
        migrations.AlterField(
            model_name='tng',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.SubCategory', verbose_name='Категория:'),
        ),
    ]
