# Generated by Django 2.2 on 2019-06-20 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190620_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='tng',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.City', verbose_name='Город:'),
        ),
    ]
