# Generated by Django 2.2 on 2019-06-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190620_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tng',
            name='age',
        ),
        migrations.AddField(
            model_name='tng',
            name='age_from',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Со скольки лет:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tng',
            name='age_up',
            field=models.IntegerField(db_index=True, default=0, verbose_name='До скольки лет:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
