# Generated by Django 2.2 on 2019-06-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20190629_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='tng',
            name='company',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='Организация:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tng',
            name='age_up',
            field=models.IntegerField(blank=True, db_index=True, verbose_name='До скольки лет:'),
        ),
        migrations.AlterField(
            model_name='tng',
            name='website',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сайт:'),
        ),
    ]
